name: inventory_optimisation_v2
channels:
  - conda-forge
  - defaults
dependencies:
    - absl-py==1.3.0
    - numpy==1.23.5
    - pandas==1.5.2
    - protobuf==4.21.12
    - python-dateutil==2.8.2
    - pytz==2022.6
    - PyYAML==6.0
    - six==1.16.0
    - pip
    - pip:
      - ortools #=9.5.2237
